### ISSUE TITLE
Недоработки новостей

### ISSUE THREAD

**Issue by Ghostlyr** [jm-organization/webmcr_gm_edition#10]
- [x] Отсутствует колонка `hidden` в запросе [news.class.php#315](https://github.com/jm-organization/webmcr_gm_edition/blob/master/upload/modules/admin/news.class.php#L315)
- [x] Не задано значение переменной $hidden [news.class.php#L336](https://github.com/jm-organization/webmcr_gm_edition/blob/master/upload/modules/admin/news.class.php#L336)
- [x] Значение `time_create` все еще создается и обновляется в JSON-массиве `data`
- [x] В `data` дублируется `uid_create`, записывающийся в собственную колонку
- [x] В запросах функций `news_list` и `news_array` отсутствуют проверки условий `hidden`:
```
$where = ($cid!==false)?"WHERE `n`.cid='$cid' AND `n`.`hidden` = 0 OR `c`.`hidden` = 0`
":"WHERE `n`.`hidden` = 0";
```
- [x] Ненадежная проверка заголовка новости на валидность [(commit)]( https://github.com/jm-organization/webmcr_gm_edition/commit/ede13a4b074de993877e6da0c61978a082d2a3cd#diff-39be821febafb80ffa640b5b8f0ed709R217)
- [x] Функция `get_preview` для просмотра отредактированной новости получает преобразованный в текст HTML код (`$text = $this->db->HSC($ar['text_html']);` )

По организации БД:
- [x] Поле `hidden` желательно переместить после `attach` для упорядоченности. Добавить комментарий к полю для упрощения разработки - Активатор скрытия новости из вывода пользователям.
- [x] Поле `img` желательно расположить перед `data`, либо после первых трех колонок, для упорядоченности. Добавить комментарий к полю для упрощения разработки - Ссылка на изображение-миниатюру новости.

**Comment by gromovjm** [comment]
>Значение time_create все еще создается и обновляется в JSON-массиве data
>В data дублируется uid_create, записывающийся в собственную колонку

Не вижу смысла тогда в поле `data` вообще.

**Comment by Ghostlyr** [comment]
Может быть и сомнительный, но есть смысл в легкой расширяемости, в хранении редко используемых или не всегда задающихся данных.

**Comment by Ghostlyr** [comment]
- [x] Не задано в функции добавления: Undefined index: PLANED_PUBLISH in /themes/default/modules/admin/news/new-add.html
- [x] В `get_preview` все еще уходят некорректные данные, обработанные safesql
- [x] {READMORE} в `get_preview` заменить на `<hr>` для понятного отображения разделения новости

**Comment by Magicfar4** [comment]
- [ ] Привести в порядок вид списка новостей в админке

**Comment by Ghostlyr** [comment]
Апну снова, чтобы не захламлять:

- [x] В `news_full` остается {READMORE}, так как он не оборачивается tinymce в теги `<p>`, как указано в `str_replace:` [modules/news.php#L348](https://github.com/jm-organization/webmcr_gm_edition/blob/master/modules/news.php#L348)
- [x] Если в новости отсутствует разделитель  `{READMORE}` , то в `news_array` зачем-то выводится [null](https://github.com/jm-organization/webmcr_gm_edition/blob/master/modules/news.php#L95), а должен бы текст новости.
