### ISSUE TITLE
Переименование колонок для удобопонятности

### ISSUE THREAD

**Issue by Ghostlyr** [jm-organization/webmcr_gm_edition#15]
Предлагаю назначить некоторым колонкам с повторяющимися именами дополнительные префиксы, указывающие на их содержимое, поскольку при большом количестве JOIN-ов  становится сложно ориентироваться в запросе и при необходимости выборки нескольких колонок с одинаковыми именами, приходится назначать им альтернативные в запросе. (ИМХО простого любителя поковыряться)

Примеры:
```
mcr_users: id -> user_id
mcr_groups: id -> group_id
mcr_news: id -> news_id
mcr_news_cats: id -> news_cat_id
```
Итд

**Comment by gromovjm** [comment]
ну а как же записи `comments.id` || `c.id` ;( 
Не стоит так делать, как по мне.
