### ISSUE TITLE
Замена системы локализации

### ISSUE THREAD

**Issue by Ghostlyr** [jm-organization/webmcr_gm_edition#16]
Текущая система локализации вызывает только ненависть по ряду причин:
- Отсутствие родительских языков: добавленный новый язык требует указания всех фраз до единой.
- Раздробленность на модули, подмодули.
- Невозможность использования фраз из других модулей, не импортируя его файл локализации.
- Сомнительная производительность.
- Бесполезность в виду отсутствия и невозможности реализации мультиязычности CMS.

Предлагаю взять пример с XenForo и многих других CMS, поддерживающих адекватную мультиязычность. 
- Хранить локализации в базе данных:  одну таблицу для фраз, с подобной же структурой, но в упрощенном варианте: `language_id`, `phrase_title`, `module_id` (для возможности быстрого удаления модульных фраз). Вторую таблицу для списка языков, зависимостей и кешированного списка фраз из предыдущей таблицы с учетом зависимостей, либо же кешировать в TXT-файл, как в текущей системе привелегий.
- Реализовать модуль в админ-панели для работы с фразами и языками.
- Реализовать возможность выбора глобального языка в админке или возможность выбора пользователем индивидуально, храня ID выбранного им языка базе данных.

Но вот что делать с фразами в JS-"локалях" - не имею понятия.

**Comment by gromovjm** [comment]
- [x] Создать таблицу фраз и таблицу языков
- [x] Собрать все фразы со всего движка и перенести в таблицу (кайоф)
- [x] Добавить функции для взаимодействия с этими таблицами
- [x] Реализовать наследственность

**Comment by gromovjm** [comment]
Осталось реализовать: 

- [x] редактирование/добавление/удаление фраз с обновлением кэша, фраз в таблице языков и если эта фраза из таблицы мастер-языка, то удаление этой фразы и с той таблицы тоже.

- [x] Выбор главного языка в списке языков (?)

- [ ] Реализовать импорт/экспорт языков.

**Comment by gromovjm** [comment]
Will be added.
