### ISSUE TITLE
Функция parse_date - A non well formed numeric value encountered

### ISSUE THREAD

**Issue by Ghostlyr** [jm-organization/webmcr_gm_edition#24]
При передаче MySQL'овского TIMESTAMP этой функции, высвечивается предупреждение:

`A non well formed numeric value encountered file: \engine\l10n.class.php on line: 380.`

**Comment by gromovjm** [comment]
Да. необходимо использовать [strtotime ](http://php.net/manual/ru/function.strtotime.php) ибо функция parse_date  принимает время в формате unix, timetsamp. 

С бд timestamp прилетает строкой, в которой время указано с точностью до милисекунды, по этому поле и именуется таймштамп, но для полного перевода в таймнштамп необходимо использовать данную функцию - [strtotime ](http://php.net/manual/ru/function.strtotime.php)
