### ISSUE TITLE
Uncaught Error: Class 'Locale' not found

### ISSUE THREAD

**Issue by andriihorpenko** [jm-organization/webmcr_gm_edition#25]
Класса попросту нету. Никакими импортами и не пахло. Ошибка ещё и на стадии установки, но если комментнуть проверку существования класса(думал, что ошибка установщика), то после установки ошибка проявила полный стэк. Чекни, Магикмэн, думаю узнал :)

**Comment by andriihorpenko** [comment]
Если это имплементация класса расширения intl, то рекомендую добавить на стадии установки helper с пояснением, что чтобы включить эту локализацию, надо расширение пыхи intl.

**Comment by gromovjm** [comment]
https://github.com/jm-organization/webmcr_gm_edition/blob/b1e006fec499ffcc4610b7c3113e83b124acb527/install/modules/start.php#L44
Ещё на стадии установки вас должно было остановить из-за того, что не установлено расширение php_intil 

> то после установки ошибка проявила полный стэк

скрипт не предусматривает таких действий. это уже намеренное нарушение кода, которое не предусамтривает поддержки :)

**Comment by andriihorpenko** [comment]
Это все очень хорошо, но все же рекомендую втыкнуть минимальное требование с упоминанием этого модуля пыхи, ибо любой смертный не догадается порыть в гуглятке, что за localization. ПасЫба :)
